GITHUB_ORG: "gs-gs,ktlg,gs-dawe"
GITHUB_CLIENT_ID: "<client id>"
GITHUB_CLIENT_SECRET: "<client secret>"
COGNITO_REDIRECT_URI: "cognito redirect URL"
GITHUB_API_URL: "https://api.github.com"
GITHUB_LOGIN_URL: "https://github.com"
GITHUB_TEAMS: "gs-gs:team1,ktlg:team2,gs-dawe:team3"
GITHUB_SCOPES: "openid read:user user:email read:org"
