on:
  push:
    tags:
      - 'v*'

name: Create Lambda Release Artefacts

jobs:
  build:
    name: Create Lambda Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run test
      - run: npx sls package

      - name: Create Tag Release
        id: create_tag_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref  }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Get tag name
        id: get-tag-name
        run: |
          tag_ref="${{github.ref}}"
          tag_name="$(echo "${tag_ref##*/}" )"
          echo "::set-output name=tag_name::$tag_name"

      - name: Upload Tag Release Asset
        id: upload_tag_release_assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '.serverless/github-cognito-openid-wrapper.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{steps.get-tag-name.outputs.tag_name}}
