name: testing

on:
  push:
  pull_request:

jobs:
  # Basic testing of the plugin to make sure its all ok
  run_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: npm test
